/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package remotemapper;

import remotemapper.exceptions.SerialException;
import com.fazecast.jSerialComm.SerialPort;
import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Vector;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.JTextArea;
import javax.swing.SwingWorker;
import javax.swing.text.DefaultCaret;
import javax.swing.text.PlainDocument;
import remoteMapper.classes.Map;
import remotemapper.classes.Rover;
import remotemapper.utility.AngleFilter;
import remotemapper.utility.LengthFilter;
import remotemapper.utility.MyIntFilter;

/**
 *
 * @author Robert Hutter
 */
public class RemoteMapper extends javax.swing.JFrame {
    private SerialHandler port;
    private Map map;
    private Rover rover;
    private File workspace;
    private File mapFile;

    /**
     * Creates new form RemoteMapper
     */
    public RemoteMapper() {
        initComponents();
        
        // Init custom components
        port = new SerialHandler ();
        wizardPage1.setLocationRelativeTo(null);
        wizardPage2.setLocationRelativeTo(null);
        wizardPage3.setLocationRelativeTo (null);
        wizardPage4.setLocationRelativeTo (null);
        loadingScreen.setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
        fileChooser = new javax.swing.JFileChooser ();
        
        // Interger filters on formatted textFields
        PlainDocument pd = (PlainDocument) mapWidthFormattedField.getDocument();
        pd.setDocumentFilter(new MyIntFilter());
        PlainDocument pd2 = (PlainDocument) mapHeightFormattedField.getDocument();
        pd2.setDocumentFilter(new MyIntFilter());
        
        PlainDocument pd3 = (PlainDocument) roverWidthFormattedField.getDocument();
        pd3.setDocumentFilter(new MyIntFilter());
        PlainDocument pd4 = (PlainDocument) roverHeightFormattedField.getDocument();
        pd4.setDocumentFilter(new MyIntFilter());
        PlainDocument pd5 = (PlainDocument) roverLengthFormattedField.getDocument();
        pd5.setDocumentFilter(new MyIntFilter());
        
        PlainDocument pd6 = (PlainDocument) obsticalMarkTextField.getDocument();
        pd6.setDocumentFilter(new LengthFilter (1));
        PlainDocument pd7 = (PlainDocument) emptySpaceMarkTextField.getDocument();
        pd7.setDocumentFilter(new LengthFilter (1));
        
        PlainDocument pd8 = (PlainDocument) positionXFormattedField.getDocument();
        pd8.setDocumentFilter (new MyIntFilter());
        PlainDocument pd9 = (PlainDocument) positionYFormattedField.getDocument();
        pd9.setDocumentFilter (new MyIntFilter());
        
        PlainDocument pd10 = (PlainDocument) headingFormattedField.getDocument();
        pd10.setDocumentFilter(new AngleFilter());
        
        positionErrorLabel.setForeground(Color.red);
        
        DefaultCaret caret = (DefaultCaret)loadingConsole.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        
        // Start application
        wizardPage1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wizardPage1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        portComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        baudRateSelector = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        encodeCharsetSelector = new javax.swing.JComboBox<>();
        decodeCharsetSelector = new javax.swing.JComboBox<>();
        start = new javax.swing.JButton();
        errorJLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        wizardPage2 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        useExistingRadio = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        browseButton = new javax.swing.JButton();
        wizardPage2ErrorLabel = new javax.swing.JLabel();
        wizardPage2Back = new javax.swing.JButton();
        fileChooser = new javax.swing.JFileChooser();
        wizardPage3 = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mapWidthLabel = new javax.swing.JLabel();
        mapWidthFormattedField = new javax.swing.JFormattedTextField();
        mapHeightLabel = new javax.swing.JLabel();
        mapHeightFormattedField = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        useDefaultMarkingsRadio = new javax.swing.JRadioButton();
        obsticalMarkLabel = new javax.swing.JLabel();
        obsticalMarkTextField = new javax.swing.JTextField();
        emptySpaceMarkLabel = new javax.swing.JLabel();
        emptySpaceMarkTextField = new javax.swing.JTextField();
        wizardPage4Next = new javax.swing.JButton();
        wizardPage3Back = new javax.swing.JButton();
        wizardPage4 = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        roverWidthFormattedField = new javax.swing.JFormattedTextField();
        roverWidthLabel = new javax.swing.JLabel();
        roverLengthLabel = new javax.swing.JLabel();
        roverLengthFormattedField = new javax.swing.JFormattedTextField();
        roverHeightLabel = new javax.swing.JLabel();
        roverHeightFormattedField = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        positionXLabel = new javax.swing.JLabel();
        positionXFormattedField = new javax.swing.JFormattedTextField();
        positionYLabel = new javax.swing.JLabel();
        positionYFormattedField = new javax.swing.JFormattedTextField();
        headingLabel = new javax.swing.JLabel();
        headingFormattedField = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        positionErrorLabel = new javax.swing.JLabel();
        about = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        loadingScreen = new javax.swing.JFrame();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel12 = new javax.swing.JPanel();
        loadingProgressBar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        loadingConsole = new javax.swing.JTextArea();
        jSeparator7 = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        statusBar = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        clock = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        wizardPage1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        wizardPage1.setTitle("Remote Mapper Setup Wizard");
        wizardPage1.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/map.png")).getImage());
        wizardPage1.setResizable(false);
        wizardPage1.setSize(new java.awt.Dimension(383, 200));

        jLabel1.setText("<html><h3>Smart Crew Remote Mapper Setup Wizard</h3></html>");

        jLabel2.setText("<html><h4>Setup a serial connection</h4></html>");

        jLabel3.setText("Port:");

        portComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        portComboBox.setToolTipText("Select the rovers serial port.");
        portComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                portComboBoxPopupMenuWillBecomeVisible(evt);
            }
        });
        portComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Baud rate:");

        baudRateSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "110", "300", "600", "1200", "2400", "4800", "9600", "14400", "19200", "38400", "57600", "115200", "128000", "256000" }));
        baudRateSelector.setSelectedIndex(11);
        baudRateSelector.setToolTipText("Select the bit rate [bit/s] used to communicate.");

        jLabel5.setText("Encode charset:");

        jLabel6.setText("Decode charset:");

        encodeCharsetSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US-ASCII", "ISO-8859-1", "UTF-8", "UTF-16BE", "UTF-16LE", "UTF-16" }));
        encodeCharsetSelector.setToolTipText("Select the character set used to decode transmissions.");

        decodeCharsetSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US-ASCII", "ISO-8859-1", "UTF-8", "UTF-16BE", "UTF-16LE", "UTF-16" }));
        decodeCharsetSelector.setToolTipText("Select the character set used to encode data to be sent.");

        start.setText("<html><h4>Next</h4></html>");
        start.setToolTipText("");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(errorJLabel)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3))
                                            .addGap(10, 10, 10)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(portComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(baudRateSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(36, 36, 36)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(decodeCharsetSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(encodeCharsetSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(portComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(encodeCharsetSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(baudRateSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(decodeCharsetSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorJLabel))
                .addGap(102, 102, 102))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout wizardPage1Layout = new javax.swing.GroupLayout(wizardPage1.getContentPane());
        wizardPage1.getContentPane().setLayout(wizardPage1Layout);
        wizardPage1Layout.setHorizontalGroup(
            wizardPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizardPage1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        wizardPage1Layout.setVerticalGroup(
            wizardPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        wizardPage2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        wizardPage2.setTitle("Remote Mapper Setup Wizard");
        wizardPage2.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/map.png")).getImage());
        wizardPage2.setResizable(false);
        wizardPage2.setSize(new java.awt.Dimension(383, 200));

        jLabel7.setText("<html><h3>Smart Crew Remote Mapper Setup Wizard</h3></html>");

        jLabel8.setText("<html><h4>Setup the workspace</h4></html>");

        jLabel9.setText("Use existing workspace:");

        useExistingRadio.setText("Yes");
        useExistingRadio.setToolTipText("Select if you want to use an existing workspace.");
        useExistingRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useExistingRadioActionPerformed(evt);
            }
        });

        jLabel10.setText("Workspace path:");

        pathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTextFieldActionPerformed(evt);
            }
        });

        nextButton.setText("<html><h4>Next</h4></html>");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        browseButton.setText("Browse");
        browseButton.setToolTipText("");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        wizardPage2Back.setText("<html><h4>Back</h4></html>");
        wizardPage2Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wizardPage2BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(wizardPage2ErrorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(wizardPage2Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(useExistingRadio))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(browseButton))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(useExistingRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wizardPage2Back, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(wizardPage2ErrorLabel))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout wizardPage2Layout = new javax.swing.GroupLayout(wizardPage2.getContentPane());
        wizardPage2.getContentPane().setLayout(wizardPage2Layout);
        wizardPage2Layout.setHorizontalGroup(
            wizardPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        wizardPage2Layout.setVerticalGroup(
            wizardPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        wizardPage3.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        wizardPage3.setTitle("Remote Mapper Setup Wizard");
        wizardPage3.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/map.png")).getImage());
        wizardPage3.setResizable(false);
        wizardPage3.setSize(new java.awt.Dimension(383, 200));

        jLabel12.setText("<html><h3>Smart Crew Remote Mapper Setup Wizard</h3></html>");

        jLabel13.setText("<html><h4>Setup the map</h4></html>");

        jLabel14.setText("Map size:");

        mapWidthLabel.setText("width");

        mapWidthFormattedField.setText("100");
        mapWidthFormattedField.setToolTipText("Select the maps width.");
        mapWidthFormattedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapWidthFormattedFieldActionPerformed(evt);
            }
        });

        mapHeightLabel.setText("height");

        mapHeightFormattedField.setText("100");
        mapHeightFormattedField.setToolTipText("Select the maps height.");

        jLabel17.setText("Markings:");

        jLabel18.setText("use default:");

        useDefaultMarkingsRadio.setSelected(true);
        useDefaultMarkingsRadio.setText("yes");
        useDefaultMarkingsRadio.setToolTipText("Select if you want to use the default map markings.");
        useDefaultMarkingsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useDefaultMarkingsRadioActionPerformed(evt);
            }
        });

        obsticalMarkLabel.setText("Obstical:");
        obsticalMarkLabel.setEnabled(false);

        obsticalMarkTextField.setColumns(1);
        obsticalMarkTextField.setText("1");
        obsticalMarkTextField.setToolTipText("Select the charactar to be used to mark an obstical on the map.");
        obsticalMarkTextField.setEnabled(false);
        obsticalMarkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obsticalMarkTextFieldActionPerformed(evt);
            }
        });

        emptySpaceMarkLabel.setText("Empty space:");
        emptySpaceMarkLabel.setEnabled(false);

        emptySpaceMarkTextField.setColumns(1);
        emptySpaceMarkTextField.setText("0");
        emptySpaceMarkTextField.setToolTipText("Select the character to be used to mark empty space on the map.");
        emptySpaceMarkTextField.setEnabled(false);
        emptySpaceMarkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptySpaceMarkTextFieldActionPerformed(evt);
            }
        });

        wizardPage4Next.setText("<html><h4>Next</h4></html>");
        wizardPage4Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wizardPage4NextActionPerformed(evt);
            }
        });

        wizardPage3Back.setText("<html><h4>Back</h4></html>");
        wizardPage3Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wizardPage3BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mapWidthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mapWidthFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mapHeightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mapHeightFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(obsticalMarkLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(obsticalMarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emptySpaceMarkLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emptySpaceMarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(useDefaultMarkingsRadio)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wizardPage4Next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wizardPage3Back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(mapWidthLabel)
                            .addComponent(mapWidthFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mapHeightLabel)
                            .addComponent(mapHeightFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(useDefaultMarkingsRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(obsticalMarkLabel)
                            .addComponent(obsticalMarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emptySpaceMarkLabel)
                            .addComponent(emptySpaceMarkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(wizardPage3Back, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wizardPage4Next, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout wizardPage3Layout = new javax.swing.GroupLayout(wizardPage3.getContentPane());
        wizardPage3.getContentPane().setLayout(wizardPage3Layout);
        wizardPage3Layout.setHorizontalGroup(
            wizardPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        wizardPage3Layout.setVerticalGroup(
            wizardPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizardPage3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        wizardPage4.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        wizardPage4.setTitle("Remote Mapper Setup Wizard");
        wizardPage4.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/map.png")).getImage());
        wizardPage4.setResizable(false);
        wizardPage4.setSize(new java.awt.Dimension(383, 200));

        jLabel19.setText("<html><h3>Smart Crew Remote Mapper Setup Wizard</h3></html>");

        jLabel20.setText("<html><h4>Setup the rover</h4></html>");

        jLabel11.setText("Dimensions (mm):");

        roverWidthFormattedField.setText("270");

        roverWidthLabel.setText("width");

        roverLengthLabel.setText("length");

        roverLengthFormattedField.setText("370");

        roverHeightLabel.setText("height");

        roverHeightFormattedField.setText("200");

        jButton2.setText("<html><h4>Finish</h4></html>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel23.setText("Position:");

        positionXLabel.setText("x");

        positionXFormattedField.setText("0");

        positionYLabel.setText("y");

        positionYFormattedField.setText("0");

        headingLabel.setText("Heading:");

        headingFormattedField.setText("0");

        jLabel27.setText("°");

        jButton1.setText("<html><h4>Back</h4></html>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(positionErrorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(4, 4, 4)
                                .addComponent(roverWidthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roverWidthFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roverLengthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roverLengthFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roverHeightLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roverHeightFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionXLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionXFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionYLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(positionYFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(headingLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(headingFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(roverWidthFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roverWidthLabel)
                    .addComponent(roverLengthLabel)
                    .addComponent(roverLengthFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roverHeightLabel)
                    .addComponent(roverHeightFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(positionXLabel)
                    .addComponent(positionXFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(positionYLabel)
                    .addComponent(positionYFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headingLabel)
                    .addComponent(headingFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(positionErrorLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout wizardPage4Layout = new javax.swing.GroupLayout(wizardPage4.getContentPane());
        wizardPage4.getContentPane().setLayout(wizardPage4Layout);
        wizardPage4Layout.setHorizontalGroup(
            wizardPage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        wizardPage4Layout.setVerticalGroup(
            wizardPage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        about.setTitle("About Remote Mapper");
        about.setAlwaysOnTop(true);
        about.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/info.png")).getImage());
        about.setResizable(false);
        about.setSize(new java.awt.Dimension(439, 300));
        about.setType(java.awt.Window.Type.POPUP);

        jLabel15.setText("<html><h2>Remote Mapper</h2></html");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel21.setText("<html><p>Robert Hutter<br />Version 1206<br />No rights reserved.</p></html>");

        jLabel22.setText("<html><div>Icons made by <a href=\"https://www.flaticon.com/authors/roundicons\" title=\"Roundicons\">Roundicons</a> from <a href=\"https://www.flaticon.com/\" title=\"Flaticon\">www.flaticon.com</a> is licensed by <a href=\"http://creativecommons.org/licenses/by/3.0/\" title=\"Creative Commons BY 3.0\" target=\"_blank\">CC 3.0 BY</a></div><br /><div>Icons made by <a href=\"https://www.flaticon.com/authors/smashicons\" title=\"Smashicons\">Smashicons</a> from <a href=\"https://www.flaticon.com/\" title=\"Flaticon\">www.flaticon.com</a> is licensed by <a href=\"http://creativecommons.org/licenses/by/3.0/\" title=\"Creative Commons BY 3.0\" target=\"_blank\">CC 3.0 BY</a></div></html>");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aboutLayout = new javax.swing.GroupLayout(about.getContentPane());
        about.getContentPane().setLayout(aboutLayout);
        aboutLayout.setHorizontalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator5))
                    .addGroup(aboutLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aboutLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        aboutLayout.setVerticalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        loadingScreen.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        loadingScreen.setTitle("Remote Mapper Wizard");
        loadingScreen.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/map.png")).getImage());
        loadingScreen.setResizable(false);
        loadingScreen.setSize(new java.awt.Dimension(383, 200));

        jLabel24.setText("<html><h3>Prepairing your workspace</h3></html>");

        loadingConsole.setEditable(false);
        loadingConsole.setColumns(20);
        loadingConsole.setRows(5);
        jScrollPane1.setViewportView(loadingConsole);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(loadingProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadingProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator6))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout loadingScreenLayout = new javax.swing.GroupLayout(loadingScreen.getContentPane());
        loadingScreen.getContentPane().setLayout(loadingScreenLayout);
        loadingScreenLayout.setHorizontalGroup(
            loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loadingScreenLayout.setVerticalGroup(
            loadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remote Mapper");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/map.png")).getImage());
        setSize(new java.awt.Dimension(830, 550));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        statusBar.setMaximumSize(new java.awt.Dimension(32767, 22));
        statusBar.setMinimumSize(new java.awt.Dimension(100, 22));
        statusBar.setPreferredSize(new java.awt.Dimension(909, 22));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        clock.setText("00:00.00");

        javax.swing.GroupLayout statusBarLayout = new javax.swing.GroupLayout(statusBar);
        statusBar.setLayout(statusBarLayout);
        statusBarLayout.setHorizontalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusBarLayout.createSequentialGroup()
                .addGap(0, 842, Short.MAX_VALUE)
                .addComponent(clock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        statusBarLayout.setVerticalGroup(
            statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusBarLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(statusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusBarLayout.createSequentialGroup()
                        .addComponent(clock)
                        .addGap(4, 4, 4))
                    .addGroup(statusBarLayout.createSequentialGroup()
                        .addComponent(jSeparator9)
                        .addGap(3, 3, 3))))
        );

        jMenu1.setText("File");

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem);

        saveAsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        saveAsMenuItem.setText("Save As...");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveAsMenuItem);

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(aboutMenuItem);

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator8)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        try {
            if (!portComboBox.getSelectedItem().equals("Select"))
            {
                port.open((String) portComboBox.getSelectedItem(), Integer.parseInt((String) baudRateSelector.getSelectedItem()), (String) decodeCharsetSelector.getSelectedItem());
                errorJLabel.setText("");
                wizardPage1.setVisible(false);
                wizardPage2.setVisible(true);
            } else
            {
                errorJLabel.setForeground(Color.red);
                errorJLabel.setText ("Please select a port.");
            }
        } catch (SerialException ex) {
            errorJLabel.setForeground(Color.red);
            errorJLabel.setText("Selected port busy. Please try again.");
            Logger.getLogger(RemoteMapper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startActionPerformed

    private void portComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portComboBoxActionPerformed

    private void portComboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_portComboBoxPopupMenuWillBecomeVisible
        // TODO add your handling code here:
        SerialPort[] ports = SerialHandler.getCommPorts();
        portComboBox.removeAllItems();
        for (SerialPort port1 : ports) {
            portComboBox.addItem(port1.getSystemPortName());
        }
        
        if (portComboBox.getItemCount() < 1)
            portComboBox.addItem("Select");
    }//GEN-LAST:event_portComboBoxPopupMenuWillBecomeVisible

    private void useExistingRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useExistingRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useExistingRadioActionPerformed

    private void pathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathTextFieldActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // TODO add your handling code here:
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        if (fileChooser.showDialog(wizardPage2, "Select workspace") == javax.swing.JFileChooser.APPROVE_OPTION)
        {
            pathTextField.setText(fileChooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        // Make sure that the workspace is valid
        pathTextField.setEditable (false);
        File ws = new File (pathTextField.getText());
        if (ws.isDirectory())
        {
            if (existingWorkspaceValid (ws))
            {
                if (useExistingRadio.isSelected())
                {
                    workspace = ws;
                    wizardPage2.setVisible (false);
                    wizardPage4.setVisible(true);
                    pathTextField.setEditable(true);
                }
                else
                {
                    if (0 == JOptionPane.showConfirmDialog(null, "Selected workspace contains valid data. Would you like to overwrite it?", "Overwrite workspace?", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION))
                    {
                        workspace = ws;
                        wizardPage2.setVisible(false);
                        wizardPage3.setVisible(true);
                    }
                    
                    pathTextField.setEditable (true);
                  }
            }
            else
            {
                if (useExistingRadio.isSelected())
                {
                    wizardPage2ErrorLabel.setForeground(Color.red);
                    wizardPage2ErrorLabel.setText("Selected workspace invalid.");
                    pathTextField.setEditable(true);
                }
                else
                {
                    workspace = ws;
                    wizardPage2.setVisible(false);
                    wizardPage3.setVisible(true);
                    pathTextField.setEditable(true);
                }
            }
            
            
        }
        else
        {
            wizardPage2ErrorLabel.setForeground(Color.red);
            wizardPage2ErrorLabel.setText("Please select a workspace.");
            pathTextField.setEditable(true);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void mapWidthFormattedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapWidthFormattedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mapWidthFormattedFieldActionPerformed

    private void useDefaultMarkingsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useDefaultMarkingsRadioActionPerformed
        // TODO add your handling code here:
        if (useDefaultMarkingsRadio.isSelected())
        {
            obsticalMarkLabel.setEnabled(false);
            obsticalMarkLabel.setForeground(Color.black);
            obsticalMarkTextField.setText("1");
            obsticalMarkTextField.setEnabled(false);
            
            emptySpaceMarkLabel.setEnabled(false);
            emptySpaceMarkLabel.setForeground(Color.black);
            emptySpaceMarkTextField.setText("0");
            emptySpaceMarkTextField.setEnabled(false);
        }
        else
        {
            obsticalMarkLabel.setEnabled(true);
            obsticalMarkTextField.setEnabled(true);
            
            emptySpaceMarkLabel.setEnabled(true);
            emptySpaceMarkTextField.setEnabled(true);
        }
        
    }//GEN-LAST:event_useDefaultMarkingsRadioActionPerformed

    private void obsticalMarkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obsticalMarkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obsticalMarkTextFieldActionPerformed

    private void emptySpaceMarkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptySpaceMarkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emptySpaceMarkTextFieldActionPerformed

    private void wizardPage4NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wizardPage4NextActionPerformed
        // TODO add your handling code here:
        // Test values
        boolean ok = true;
        
        if (mapWidthFormattedField.getText().isEmpty())
        {
            ok = false;
            mapWidthLabel.setForeground(Color.red);
        }
        else
            mapWidthLabel.setForeground(Color.black);
        
        if (mapHeightFormattedField.getText().isEmpty())
        {
            ok = false;
            mapHeightLabel.setForeground(Color.red);
        }
        else
            mapHeightLabel.setForeground(Color.black);
        
        if (obsticalMarkTextField.getText().isEmpty())
        {
            ok = false;
            obsticalMarkLabel.setForeground(Color.red);
        }
        else
            obsticalMarkLabel.setForeground(Color.black);
        
        if (emptySpaceMarkTextField.getText().isEmpty())
        {
            ok = false;
            emptySpaceMarkLabel.setForeground(Color.red);
        }
        else
            emptySpaceMarkLabel.setForeground(Color.black);
        
        if (ok)
        {
            wizardPage3.setVisible(false);
            wizardPage4.setVisible(true);
        }
    }//GEN-LAST:event_wizardPage4NextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean ok = true;
        
        if (roverHeightFormattedField.getText().isEmpty())
        {
            ok = false;
            roverHeightLabel.setForeground(Color.red);
        }
        else
            roverHeightLabel.setForeground(Color.black);
        
        if (roverLengthFormattedField.getText().isEmpty())
        {
            ok = false;
            roverLengthLabel.setForeground(Color.red);
        }
        else
            roverLengthLabel.setForeground(Color.black);
        
        if (roverWidthFormattedField.getText().isEmpty())
        {
            ok = false;
            roverWidthLabel.setForeground(Color.red);
        }
        else
            roverWidthLabel.setForeground(Color.black);
        
        if (positionXFormattedField.getText().isEmpty())
        {
            ok = false;
            positionXLabel.setForeground(Color.red);
        }
        else
            positionXLabel.setForeground (Color.black);
        
        if (positionYFormattedField.getText().isEmpty())
        {
            ok = false;
            positionYLabel.setForeground(Color.red);
        }
        else
            positionYLabel.setForeground (Color.black);
        
        if (headingFormattedField.getText().isEmpty())
        {
            ok = false;
            headingLabel.setForeground(Color.red);
        }
        else
            headingLabel.setForeground(Color.black);
        
        // Check to make sure position is valid:
        if (!useExistingRadio.isSelected())
        {
            if (Integer.parseInt(positionXFormattedField.getText()) > Integer.parseInt (mapWidthFormattedField.getText()))
            {
                positionErrorLabel.setText("Invalid position. X too big.");
                ok = false;
            }
            else if (Integer.parseInt(positionYFormattedField.getText()) > Integer.parseInt(mapHeightFormattedField.getText()))
            {
                positionErrorLabel.setText("Invalid position. Y too big.");
                ok = false;
            }
            else
                positionErrorLabel.setText("");
        }
        
        if (ok)
        {
            wizardPage4.setVisible(false);
            loadingScreen.setVisible(true);
            
            // load workspace
            // If using an existing workspace, parse map
            if (useExistingRadio.isSelected())
            {
                loadingConsole.append("Loading map...\n");
                mapFile = new File (pathTextField.getText() + File.separator + "map.d");

                loadingProgressBar.setMaximum((int) mapFile.length());

                LoadMap lm = new LoadMap(mapFile);

                lm.execute();
                
                // Create new rover
                rover = new Rover (Integer.parseInt(positionXFormattedField.getText()), Integer.parseInt(positionYFormattedField.getText()), Integer.parseInt(headingFormattedField.getText()), Integer.parseInt(roverWidthFormattedField.getText()), Integer.parseInt(roverLengthFormattedField.getText()));
            }
            else
            {
                // Create new map
                loadingConsole.append("Creating new map...\n");
                map = new Map (Integer.parseInt(mapWidthFormattedField.getText()), Integer.parseInt(mapHeightFormattedField.getText()), obsticalMarkTextField.getText().charAt(0), emptySpaceMarkTextField.getText().charAt(0));
                loadingConsole.append ("Done...\n");
                
                mapFile = new File (workspace.getPath() + File.separator + "map.d");
                
                loadingConsole.append ("Saving map...\n");
                
                SaveMap sm = new SaveMap (map, mapFile, loadingProgressBar, loadingConsole);
                
                sm.execute();
                
                // Create new rover
                rover = new Rover (Integer.parseInt(positionXFormattedField.getText()), Integer.parseInt(positionYFormattedField.getText()), Integer.parseInt(headingFormattedField.getText()), Integer.parseInt(roverWidthFormattedField.getText()), Integer.parseInt(roverLengthFormattedField.getText()));
                this.setName("Remote Mapper ["+workspace.getName()+"] on ["+port.portName()+"]");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        about.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        about.setLocationRelativeTo (null);
        about.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit (0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void wizardPage2BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wizardPage2BackActionPerformed
        // TODO add your handling code here:
        port.close();
        wizardPage2.setVisible(false);
        wizardPage1.setVisible (true);
    }//GEN-LAST:event_wizardPage2BackActionPerformed

    private void wizardPage3BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wizardPage3BackActionPerformed
        // TODO add your handling code here:
        wizardPage3.setVisible(false);
        wizardPage2.setVisible(true);
    }//GEN-LAST:event_wizardPage3BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        wizardPage4.setVisible(false);
        
        if (useExistingRadio.isSelected ())
            wizardPage2.setVisible(true);
        else
            wizardPage3.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
        SaveMap sm = new SaveMap (map, mapFile);
        sm.execute();
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        // TODO add your handling code here:
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
        if (fileChooser.showDialog(this, "Save As") == javax.swing.JFileChooser.APPROVE_OPTION)
        {
            SaveMap sm = new SaveMap (map, fileChooser.getSelectedFile());
            sm.execute();
        }
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoteMapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoteMapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoteMapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoteMapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoteMapper();
            }
        });
    }
    
    private boolean existingWorkspaceValid (File ws)
    {
        if (new File (ws.getPath() + File.separator +"map.d").isFile())
        {
            // Continue
            return true;
        }
        
        return false;
    }
    
    private void cleanupWizard ()
    {
        wizardPage1.dispose();
        wizardPage2.dispose();
        wizardPage3.dispose();
        wizardPage4.dispose();
        loadingScreen.dispose();
    }
    
    private void loadMainFrame ()
    {
        cleanupWizard ();
        setTitle("Remote Mapper ["+workspace.getName()+"] on ["+port.portName()+"]");
        
        TimeKeeper tk = new TimeKeeper (clock);
        tk.execute();
        
        setVisible (true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame about;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JComboBox<String> baudRateSelector;
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel clock;
    private javax.swing.JComboBox<String> decodeCharsetSelector;
    private javax.swing.JLabel emptySpaceMarkLabel;
    private javax.swing.JTextField emptySpaceMarkTextField;
    private javax.swing.JComboBox<String> encodeCharsetSelector;
    private javax.swing.JLabel errorJLabel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JFormattedTextField headingFormattedField;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea loadingConsole;
    private javax.swing.JProgressBar loadingProgressBar;
    private javax.swing.JFrame loadingScreen;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JFormattedTextField mapHeightFormattedField;
    private javax.swing.JLabel mapHeightLabel;
    private javax.swing.JFormattedTextField mapWidthFormattedField;
    private javax.swing.JLabel mapWidthLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel obsticalMarkLabel;
    private javax.swing.JTextField obsticalMarkTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JComboBox<String> portComboBox;
    private javax.swing.JLabel positionErrorLabel;
    private javax.swing.JFormattedTextField positionXFormattedField;
    private javax.swing.JLabel positionXLabel;
    private javax.swing.JFormattedTextField positionYFormattedField;
    private javax.swing.JLabel positionYLabel;
    private javax.swing.JFormattedTextField roverHeightFormattedField;
    private javax.swing.JLabel roverHeightLabel;
    private javax.swing.JFormattedTextField roverLengthFormattedField;
    private javax.swing.JLabel roverLengthLabel;
    private javax.swing.JFormattedTextField roverWidthFormattedField;
    private javax.swing.JLabel roverWidthLabel;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton start;
    private javax.swing.JPanel statusBar;
    private javax.swing.JRadioButton useDefaultMarkingsRadio;
    private javax.swing.JRadioButton useExistingRadio;
    private javax.swing.JFrame wizardPage1;
    private javax.swing.JFrame wizardPage2;
    private javax.swing.JButton wizardPage2Back;
    private javax.swing.JLabel wizardPage2ErrorLabel;
    private javax.swing.JFrame wizardPage3;
    private javax.swing.JButton wizardPage3Back;
    private javax.swing.JFrame wizardPage4;
    private javax.swing.JButton wizardPage4Next;
    // End of variables declaration//GEN-END:variables

    class TimeKeeper extends SwingWorker<Void, Void>
    {
        private JLabel display;
        
        public TimeKeeper (JLabel display)
        {
            this.display = display;
        }
        
        @Override
        protected Void doInBackground() throws Exception {
            for (; ;)
            {
                display.setText(LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm.ss")));
                Thread.sleep(1000);
            }
        }
    }
    
    class LoadMap extends SwingWorker<Map, Integer>
    {
        File mapFile;

        LoadMap (File mapFile)
        {
            this.mapFile = mapFile;
        }
        
        @Override
        protected void process (List<Integer> chunks)
        {
            int i = chunks.get(chunks.size()-1);
            loadingProgressBar.setValue(i);
        }

        @Override
        public Map doInBackground() throws IOException
        {
            FileReader in = new FileReader(mapFile);
            int c, y = 0;

            // Buffer map
            Vector<Vector<Character>> b = new Vector<Vector<Character>>();
            b.add(new Vector<Character>());

            char obM = (char) in.read();
            in.skip(1);
            char esM = (char) in.read();
            in.skip(1);

            int i = 4;
            long max = mapFile.length();

            while ((c = in.read()) != -1)
            {
                    if (c == '\n')
                    {
                            y++;
                            b.add(new Vector<Character>());
                    }
                    else
                    {
                            b.get(y).add((char) c);
                    }

                if (++i % 100 == 0)
                    publish (i);
            }

            in.close();

            int capX = b.get(0).size() + 1;
            int capY = b.size() -1;

            char[][] m = new char[capY][capX];

            for (y = 0; y < capY; y++)
            {
                    for (int x = 0; x < capX - 1; x++)
                    {
                            m[y][x] = b.get(y).get(x);
                    }
                    m[y][capX - 1] = 10;
            }

            return new Map (m, obM, esM);
        }
        
        @Override
        public void done ()
        {
            try
            {
                map = get();
                loadingConsole.append("Done...\n");
                
                loadingScreen.setVisible(false);
                loadMainFrame();
            }
            catch (InterruptedException ex)
            {
                Logger.getLogger(RemoteMapper.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch (ExecutionException ex)
            {
                Logger.getLogger(RemoteMapper.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
    
    class SaveMap extends SwingWorker <Void, Integer>
    {
        private JProgressBar jpb;
        private final Map toSave;
        private final File out;
        private JTextArea log;
        
        public SaveMap (Map toSave, File out, JProgressBar jpb, JTextArea log)
        {
            this.toSave = toSave;
            this.out = out;
            this.jpb = jpb;
            this.log = log;
        }
        
        public SaveMap (Map toSave, File out)
        {
            this.toSave = toSave;
            this.out = out;
        }

        @Override
        protected Void doInBackground() throws Exception {
            final char[][] d = map.getMap();
            if (jpb != null)
                jpb.setMaximum(d.length * d[0].length);
            FileWriter out = new FileWriter(this.out.getCanonicalPath(), false);

            // Write markers
            out.write (String.valueOf(map.getObsticalMark()) + "\n");
            out.write (String.valueOf(map.getEmptySpaceMark()) + "\n");

            int i = 0;
            
            // Write map raw data
            for (int y = 0; y < d.length; y++)
            {
                    for (int x = 0; x < d[y].length; x++)
                    {
                            out.write(d[y][x]);
                            publish (++i);
                    }
            }

            out.flush();
            out.close();
                
            return null;
        }
        
        @Override
        protected void process (List<Integer> chunks)
        {
            int i = chunks.get(chunks.size()-1);
            if (jpb != null)
                jpb.setValue(i);
        }
        
        @Override
        protected void done ()
        {
            if (log != null)
            {
                log.append ("Done...\n");
            
                if (log.equals(loadingConsole))
                {
                    loadingScreen.setVisible(false);
                    loadMainFrame();
                }
            }
        }
        
    }
}